baseURL = "https://maxturgeon.ca/f21-data2010/"
languageCode = "en-ca"
title = "DATA 2010 - Fall 2021"
theme = "book"
ignoreFiles = ["_files$", "_cache$"]

[params]
BookMenuBundle = "/menu"
BookToC = false
BookSearch = false
